### PR TITLE
[#5] Fix: Deprecation warnings with set-output

### LINKED ISSUE #5: Fix: Deprecation warnings with set-output
## Issue

Projects like Compass have a lot of warnings on their GitHub Action workflows:

image

This is due to the deprecation for `set-ouput`: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

## Expected

Using  `nimblehq/branch-tag-action` should not trigger deprecation warnings.

## Steps to reproduce

Go to https://github.com/nimblehq/compass/actions/runs/3547382579

### PR DESCRIPTION
**Pull request by olivierobert**
Closes #5 

## What happened

Update the entrypoint hell shell script with the new syntax to declare the output.

## Insights

See official documentation: [github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

## Proof Of Work

Requires to be tested manually on Compass

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -15,4 +15,4 @@ else
 fi
 
 echo "BRANCH_TAG=$BRANCH_TAG" >> $GITHUB_ENV
-echo "::set-output name=branch_tag::$BRANCH_TAG"
+echo "name=branch_tag::$BRANCH_TAG" >> $GITHUB_OUTPUT
```
Comment (hoangmirs) [inline entrypoint.sh]: Following the blog documentation, I think it should be the same as declaring ENV:
```suggestion
echo "branch_tag=$BRANCH_TAG" >> $GITHUB_OUTPUT
```

Comment (olivierobert) [reply entrypoint.sh]: You are right. Fixed in [a86dd9c](https://github.com/nimblehq/branch-tag-action/pull/6/commits/a86dd9c4a2a4cf19b770dd001fc2fa7c66014dcf)

**Review by hoangmirs — APPROVED** [review]
